# Traefik Static Configuration
# Docs: https://doc.traefik.io/traefik/operations/static-configuration/

api:
  dashboard: true

ping: {}

providers:
  file:
    directory: /etc/traefik/dynamic
    watch: true

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
          permanent: true
  websecure:
    address: ":443"

metrics:
  prometheus: {}

accessLog: {}

log:
  level: WARN

# Let's Encrypt TLS certificates via ACME
certificatesResolvers:
  letsencrypt:
    acme:
      tlsChallenge: {}
      email: admin@yomu.my.id
      storage: /etc/traefik/acme.json