http:
  routers:
    frontend-router:
      rule: "Host(`yomu.my.id`) || PathPrefix(`/`)"
      service: frontend-green
      entryPoints:
        - web

    java-router:
      rule: "PathPrefix(`/api/java`)"
      service: java-green
      entryPoints:
        - web
      middlewares:
        - strip-java-prefix

    rust-router:
      rule: "PathPrefix(`/api/rust`)"
      service: rust-green
      entryPoints:
        - web
      middlewares:
        - strip-rust-prefix

    grafana-router:
      rule: "PathPrefix(`/grafana`)"
      service: grafana@docker
      entryPoints:
        - web
      middlewares:
        - strip-grafana-prefix

    prometheus-router:
      rule: "PathPrefix(`/prometheus`)"
      service: prometheus@docker
      entryPoints:
        - web
      middlewares:
        - strip-prometheus-prefix

  middlewares:
    strip-java-prefix:
      stripPrefix:
        prefixes:
          - "/api/java"

    strip-rust-prefix:
      stripPrefix:
        prefixes:
          - "/api/rust"

    strip-grafana-prefix:
      stripPrefix:
        prefixes:
          - "/grafana"

    strip-prometheus-prefix:
      stripPrefix:
        prefixes:
          - "/prometheus"

  services:
    frontend-green:
      loadBalancer:
        servers:
          - url: "http://frontend-green:3000"

    java-green:
      loadBalancer:
        servers:
          - url: "http://java-green:8080"

    rust-green:
      loadBalancer:
        servers:
          - url: "http://rust-green:8080"