http:
  routers:
    frontend-router:
      rule: "Host(`yomu.my.id`)"
      service: frontend-blue-svc
      entryPoints:
        - websecure
      tls:
        certResolver: letsencrypt

    java-router:
      rule: "Host(`java.yomu.my.id`)"
      service: java-blue-svc
      entryPoints:
        - websecure
      tls:
        certResolver: letsencrypt

    rust-router:
      rule: "Host(`rust.yomu.my.id`)"
      service: rust-blue-svc
      entryPoints:
        - websecure
      tls:
        certResolver: letsencrypt

    frontend-staging-router:
      rule: "Host(`staging.yomu.my.id`)"
      service: frontend-staging-svc
      entryPoints:
        - websecure
      tls:
        certResolver: letsencrypt

    java-staging-router:
      rule: "Host(`java-staging.yomu.my.id`)"
      service: java-staging-svc
      entryPoints:
        - websecure
      tls:
        certResolver: letsencrypt

    rust-staging-router:
      rule: "Host(`rust-staging.yomu.my.id`)"
      service: rust-staging-svc
      entryPoints:
        - websecure
      tls:
        certResolver: letsencrypt

    grafana-router:
      rule: "Host(`monitoring.yomu.my.id`)"
      service: grafana-svc
      entryPoints:
        - websecure
      tls:
        certResolver: letsencrypt

    prometheus-router:
      rule: "Host(`monitoring.yomu.my.id`) \u0026\u0026 PathPrefix(`/prometheus`)"
      service: prometheus-svc
      middlewares:
        - strip-prometheus
      entryPoints:
        - websecure
      tls:
        certResolver: letsencrypt

    http-catchall:
      rule: "HostRegexp(`{host:.+}`)"
      service: traefik-echo
      entryPoints:
        - web

  middlewares:
    strip-prometheus:
      stripPrefix:
        prefixes:
          - /prometheus

  services:
    frontend-blue-svc:
      loadBalancer:
        servers:
          - url: "http://frontend-blue:3000"

    java-blue-svc:
      loadBalancer:
        servers:
          - url: "http://java-blue:8080"

    rust-blue-svc:
      loadBalancer:
        servers:
          - url: "http://rust-blue:8080"

    frontend-staging-svc:
      loadBalancer:
        servers:
          - url: "http://frontend-staging:3000"

    java-staging-svc:
      loadBalancer:
        servers:
          - url: "http://java-staging:8080"

    rust-staging-svc:
      loadBalancer:
        servers:
          - url: "http://rust-staging:8080"

    grafana-svc:
      loadBalancer:
        servers:
          - url: "http://grafana:3000"

    prometheus-svc:
      loadBalancer:
        servers:
          - url: "http://prometheus:9090"

    traefik-echo:
      loadBalancer:
        servers:
          - url: "http://127.0.0.1:9999"
