http:
  routers:
    grafana-router:
      rule: "Host(`monitoring.yomu.my.id`)"
      service: grafana-svc
      entryPoints:
        - websecure
      tls: {}

    prometheus-router:
      rule: "Host(`monitoring.yomu.my.id`) && PathPrefix(`/prometheus`)"
      service: prometheus-svc
      entryPoints:
        - websecure
      tls: {}

    http-catchall:
      rule: "HostRegexp(`{host:.+}`)"
      service: traefik-echo
      entryPoints:
        - web

  services:
    grafana-svc:
      loadBalancer:
        servers:
          - url: "http://grafana:3000"

    prometheus-svc:
      loadBalancer:
        servers:
          - url: "http://prometheus:9090"

    traefik-echo:
      loadBalancer:
        servers:
          - url: "http://127.0.0.1:9999"